apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterautoscaler.yaml
  - machineautoscaler-gpu-g5-2a.yaml
  - machineautoscaler-gpu-g5-2b.yaml
  - machineautoscaler-gpu-g5-2c.yaml
  - machineautoscaler-gpu-g4dn-2a.yaml
  - machineautoscaler-gpu-g4dn-2b.yaml
  - machineautoscaler-gpu-g4dn-2c.yaml
