apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loan-agent

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - sandbox.yaml
  - startup.yaml
  - service.yaml
  - route.yaml
  - sealed-loan-agent-auth.yaml
  - sealed-openshell-client-tls.yaml
  - network-policy-open-webui.yaml
  - network-policy-router.yaml

configMapGenerator:
- name: loan-agent-openshell-policy
  files:
  - sandbox-policy.rego
  - policy.yaml

generatorOptions:
  disableNameSuffixHash: true
