---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loan-agent-auth
  namespace: loan-agent
spec:
  encryptedData:
    llm-api-key: AgBneV6HZxqGUmPlsfdLU0njGH81xJzExj+3FsXLQ/S2ZBILcfSNul7gRd3LlZOKLFnTkMh/d7S76BX922qesW9jt/5ZvfkMm32UeAXAU6roygj4fXiGtfTSEkhn62JmwPmxcQ7mYl4oA2M9hcLkVPaLPYicS7A9NnB53XwbIAyuFUQkRXKpWmXPk0wTxY7etfOJypM4czoih1OCrR6l0Jp2+3wvmoQUbGrNIr9jEwZydA3tu71x/Q91BULZ9EBhILy3zQZUYPepGhLmU6h4c9PoOC0+DOoRq5h56czvDTvAOd1tlEsj0afllXP+kgeRAbvxhR9xcun5w7eFIAKqwf2F5Jh7Z9H8E8bFafx8T7KH2LDQBN2ALMIAfAqqd2iXKo9SIacf4C9HfTOTfkrYiD67d0FJ6SoQThrGB0LB2tz7IscVQyYtSimTrAzaT2GsxWWBwK7RyEZnRuAuCsB0Wb9Gr8Ojimczc1GCpUSqBd0y2L88o+ZbGwzxlkPkgmJtJV84PHizbIqhH50dwOJ+PHdBE3irtGZODpl5x5qvQ2Dg5vr7RMdzLKUoU5Vp2XaVeeY4ObLDrNfTdfDuGIjOA6GeYva9DcJazzjhla6awUvN3uQJMY+wIqWpe2GfLA6ZfomUdgiNJtZ5AZvAjiIhvD5rt9TWzzHBrVwmo+PxGwIXM1cgvM3vYVYU9BphRyJjnMP/utVJoHGO59qDuWLuzbifeY4qKl/RuQAgWFiXaEugroCf9NWkfO7dXBOx1n5rTGVSM9xrMqhy4mC7YfO7Q9tpE73N
  template:
    metadata:
      name: loan-agent-auth
      namespace: loan-agent
    type: Opaque
