apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - hardware-profile.yaml
  - pvc.yaml
  - workbench.yaml
  - lmeval-job.yaml
  - llm-inference-service.yaml
