apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fine-tuning-shared
  namespace: fine-tuning-demo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: nfs-rwx-pv
  resources:
    requests:
      storage: 50Gi
