apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fine-tuning-workbench
  namespace: fine-tuning-demo
  labels:
    opendatahub.io/dashboard: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
