[extend]
useDefault = true

[allowlist]
paths = [
  '''helm-deploy/chart/templates/.*''',
  '''\.pre-commit-config\.yaml''',
  '''sealed-.*\.yaml''',
  '''.*-sealed\.yaml''',
  '''redhat/rhoai/v3\.5/base/10-agenthive/secrets/.*\.yaml''',
  '''redhat/rhoai/v3\.5/base/03-workloads/agents/ocp-virt-agent/sandbox/.*\.yaml''',
  '''redhat/rhoai/v3\.5/base/03-workloads/agents/ocp-virt-agent/sealed-secrets/.*\.yaml''',
  '''redhat/rhoai/v3\.5/setup/.*-sealed\.yaml''',
  '''\.claude/.*''',
]

[[rules]]
id = "rh-registry-service-account"
description = "Red Hat registry service account token"
regex = '''eyJhbGciOiJSUzUxMiJ9\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+'''
keywords = ["eyJhbGciOiJSUzUxMiJ9"]

[[rules]]
id = "rh-sso-offline-token"
description = "Red Hat SSO offline token"
regex = '''eyJhbGciOiJIUzUxMiIsInR5cCI[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+'''
keywords = ["eyJhbGciOiJIUzUxMiIsInR5cCI"]
