---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-keycloak-client-secret
  namespace: ocp-mcp-server
spec:
  encryptedData:
    client-secret: AgAUB4gEFRf5G+qEfV51QE907494n6m5on3c/tiUbzyQRa1CFr6ASUBWKXh6ZUgYrcEL/W/TXR7HctDj1TOR13PBYdbWvUBfyBcCXsOdM25UIq9kteYXVoLFj5ulRlVsBD826FTU2kZpsc0FldQu30dbtmjr2JWwW0yuJz80XaFR7LTEAF90ccUr4KzbjqjL6/FLp8vYGQEyJcni+CQM/I8wJbuqzBNj0qEvEE/uF4qn9CgxFnBO1N4lyvg5IkuLxXA7tJ+dd1gHYhRUXiXojafnFGRCBAJOEsNLUADYr2+EpMavhVs3pmYQ0J8j32pLdLHtgQwKoAYjsOjcVBzm2nY2yt3i/y8gU6dtoA5vYmnTmz3679I+epx9E/iuh53P7TlUqsvPG4rxW2nOS/hRlyvUUFwF0mnYV7KU4jKwwMK81y2B8wrlR38mSyyXHjw9+Baa0fRu8Q1udsDCMZ0nrUHq0T20fy9U65OhwOUvfYRHvG4iyN63yeY0xpxM91paowDvC/f83uF9MQiNSHAfyXnCQ2z92GID+Xkd784Ta2h62vGbkxZC7VVAnNGdz4S0NaSgBfhXT1eAwMezFXTTNUvXRGy1X/2PMfIfsn+Ub58Gy0oJ/YUkq8sEVkbNtFVrqbDpHXkjwDnzw48yCjwF9YSQviRfHb9REH7TRIvm3qvr7RmUgaV+jYD3eQF7gCiEuAkbmfojTVcTs2+ApYXLWHOTvzAeBsOXMcvJoFV4hudmbg==
  template:
    metadata:
      name: mcp-keycloak-client-secret
      namespace: ocp-mcp-server
