apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: nemo-guardrails
  namespace: redhat-ods-applications
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  nemoConfigs:
    - name: nemo-guardrails-config
      configMaps:
        - nemo-guardrails-config
      default: true
  replicas: 1
