apiVersion: v1
kind: Namespace
metadata:
  name: gemini-external
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/generated-namespace: "true"
    maas.opendatahub.io/gateway-access: "true"
  annotations:
    openshift.io/display-name: "Gemini External Models"
