apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  namespace: milvus
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: milvus-standalone
  ports:
    - name: grpc
      port: 19530
      targetPort: 19530
    - name: http
      port: 9091
      targetPort: 9091
