---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-api-secret
  namespace: autorag
spec:
  encryptedData:
    llm-api-key: AgBoerIicUarncd5qHfr2efvowmTBqJfy2CTNEKfvzipq7+rOAxu4J2gEHPF6nqoFidwUHexPF/pUjgO18v2e+D7GA4bepVrPDZZJFHryrshx81cnThss3mX56VHylND9eW1FK9pcQoxFWH8OEaYV+xjRgoFM7UpxGLUvI2sqqbqEfY793ZIcw28pfQ3jnnhIFC35t33wf+B3YzCYYnsbLUuhtG14F4ut/NLT9F6OIsWz0m6V2Pb4IfNJj8CnBnPzQn53ElhEDgTxJcKnIYVi6PPzxDeTKvhpdRzoQ2zv4KhXo61J2025aZZaiVIDnZJIU8mZbXKl2KWmkjWl0CBQ5cNZ8JLR+HLnpsz2RqRfny6mepFt5jT15vJcA1RZPjvAaHyykXSumi/lQS2UfE51Vz+7vVo+kOa473Ox5a6Arowb+zI6rALY8O8kZDDT7KewWiim+a6JpkgvvHVs151TOjmuN/dH+a6/78C/YC36JxCIlqCJ6HwscrlFk/dVSJN9pJ/drvXzBRIAdKTe5sp14rn+enVTNhh4m6rZG8ZvnMJXL82K4zmVZ2AZrcfmkrRu7mABz38NjnPIeUzeu10GC7KM1MFnIw28LyGX3uxwMtW1YYNoAFuC/tfG/r114idDYU+4I+SXf/rcBDR5Ig1SG8rrA4kzrOF19wL+pcC8RYHOg1d+6jgPuIfw/CYyNJ/TYEK7whhl1IqeoAlVZsLxdIbkBDS8w==
  template:
    metadata:
      name: llm-api-secret
      namespace: autorag
    type: Opaque
