apiVersion: v1
kind: Service
metadata:
  name: amortized-server
  namespace: amortized
  labels:
    app: amortized
    component: server
spec:
  type: ClusterIP
  selector:
    app: amortized
    component: server
  ports:
    - name: http
      port: 8000
      targetPort: http
