apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amortized-server-data
  namespace: amortized
  labels:
    app: amortized
    component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
