apiVersion: v1
kind: ServiceAccount
metadata:
  name: amortized-server
  namespace: amortized
  labels:
    app: amortized
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amortized-minio
  namespace: amortized
  labels:
    app: amortized
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amortized-mlflow
  namespace: amortized
  labels:
    app: amortized
