apiVersion: v1
kind: Service
metadata:
  name: amortized-studio
  namespace: amortized
  labels:
    app: amortized
    component: studio
spec:
  type: ClusterIP
  selector:
    app: amortized
    component: studio
  ports:
    - name: http
      port: 8080
      targetPort: http
