---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secret
  namespace: fine-tuning-demo
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCXPGM1BZoXzQ7wMutky1n15OSxWI/9dC6DcL5NG3yngNtePFCqfvPKsEaNUl1WuJslBsMfd2EVkmMP57ZngP7qyPwS+uSiZX5sXOyx0w2DiOnshmLY8BhjsBtW3iI6SL6p2cPa7gAlfMs9DcFoKYer4V2gNXXDwMxOqeCUOnH/GEOYZpquQ+8nisOIEkXpQm/y7kBYj43DXCCPvGEycWWRh97m1U9ZyoxdqO4lDY451SmkdyCVaiJh78O82FBl9KvOAew6apD/J2FunaloJb3WvShM7jZsksQF0Xh9D5FlzcjI5qcpSkP0CaXOhTML92QDwaMCE1SKoH7uXsu3+94JQQg4SYIvgzBu4ciGO1NzBWSq3P5QZ0f/fX0fiQf9A51m2bC4M/Nhuw0reCKSuCCLzad0GR0aL5K5/Nex5oQz3fsbAgsNcIHfjzn/d3mL1U/Y9OFiWcnqJ63UjnMX+nkQ+SdIcrhnCXThoNUx8Bl52FtbF385qJO2y00A8P+pSrpL4yr3kzSr2+VPF9djMP4dYP1g9c56t10IdCQex+Aksu5cpY1Q9LIqQUyLO7fPe11akIY3w9rmbGG/7Vvhj9nC6QzAFXVtluUVl3eJ6HOyf+58FFQ/4BYI9akyjA8yKZutL+biBr9wH5iSdGUh6ur4r5hlysnceMJRFAuTjgQILDvCGEIlm2eWOROIJH9ZGi8=
    AWS_SECRET_ACCESS_KEY: AgBN85VQr5msuZmT18LM4OJaHpNjxHnB8FPjIySHvmfoud9n2caGdCpypUqVsxSN5MkCRcg5YG0C3IkQUepNJjlAsawqauNn4Qihi1PohyjZzC42XWIUhZsD8dcUODGtrF3Wtq0n8OsFgS6KTuavU55oehbLQhYIV/R6UZsryFSlb2l+OMmFXA93mz4QBz95qyiKcqA/sCMNSDWN5imMA03IQhJ/VdH18JcKlt5OXuRnNH/tv36QzpM3dLtMFxIMDvYIty7m2/rYpjQjhkjFY5hHwpJJBTBN0VkLnbeNP9rUuP+sPVaAydvxUB/HVYuRet4JdDzhhfCc65hMX+PzHSRscDXkqF+rZjXYNO7wUdqUaSCBDaREdejJoZJ3eCGqWQzmxm5tZ0f6bX9/urITVeCBazPQA/WHdexqPs5Y6fVSLX1qPFUJywP2IhT9fTLpUgvJ0IrIz1c8T+xOMaPWO51k8JDs9woHSqsuCWTeUJ3EquQg8HtLxomUES2b1BMJxqa+ZYv/CH6rzzVK7YKIQHqX6h4ZwDVt1x4MWgUJTBR646ErijuldZwJTcEMMp6E5jaG3hRrZovGhCY3tHlzK/wWimelXRzHMtQGLYTSkA2cQ9DgNTtmPmQ8gm/qo78vt31DEE1sUZTGdUmyvngfOufVu1sc9JaRtXdO7AcE0I+uULrUUgUMaFUPX+YiRWlmFmw=
  template:
    metadata:
      name: s3-secret
      namespace: fine-tuning-demo
