apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: openshift-mcp-server
  namespace: mcp-system
spec:
  toolPrefix: "openshift_"
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: openshift-mcp-server-route
    namespace: openshift-mcp-server
