apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/03-workloads/amortized
  - sealed-s3-secret.yaml
  - sealed-db-secret.yaml
  - sealed-opencode-maas.yaml

images:
  - name: ghcr.io/amortized-ai/amortized
    newName: image-registry.openshift-image-registry.svc:5000/amortized/amortized-server
    newTag: a268ab0
  - name: ghcr.io/amortized-ai/studio
    newName: image-registry.openshift-image-registry.svc:5000/amortized/amortized-studio
    newTag: df7cd80

patches:
  - target:
      kind: ConfigMap
      name: amortized-config
    patch: |
      - op: replace
        path: /data/AMORTIZED_MLFLOW_TRACKING_URI
        value: "http://mlflow.amortized.svc.cluster.local:5000"
      - op: replace
        path: /data/AMORTIZED_S3_BUCKET
        value: "amortized"
