apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/03-workloads/amortized
  - sealed-s3-secret.yaml
  - sealed-db-secret.yaml

patches:
  - target:
      kind: ConfigMap
      name: amortized-config
    patch: |
      - op: replace
        path: /data/AMORTIZED_MLFLOW_TRACKING_URI
        value: "http://mlflow.amortized.svc.cluster.local:5000"
      - op: replace
        path: /data/AMORTIZED_S3_BUCKET
        value: "amortized"
