---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dspa-db-password
  namespace: rfp-agent
spec:
  encryptedData:
    password: AgCWRl2cik1WVAwQb014c14304l14gg2JUof+l3VVVrgpdB6dNsAt2iVfpnvdSxYxFSRQ3cJ2mT2cawDqYqub4LhtcEiztbs36MSUXAZbSadQH1iZahxYXAiD8FRXfEb7OLMXdyKnLUiDrupbE1Dc6DR6uX8QXpmNFKZoqfhKFVTuPFuon5hxUNea7UJxIzWdpi2LN8ToJ3oqP6jORwcPoe80bmGInfvm4cwBvsceEuqdG/MNIuoWpbKBI8Vv5RntY+W8GmFKOTg1O95fMEbY1u/WocVHonipAzZBjaKUkOwn58gerGUC8SvInVBF29fyPbohQ8ZOjHRmHMFixmhA4KRQNtDpGwRbkV3v/gSjESdAuIxAAddyx9ekVfc/fUai7tu7TK1HWHOmQv2XTL2XssZ5wGhTx7JdbvuLAa7kWpSSgtMztJDaXFsJipx/8KXR/CGT+MZTfRPKlQ7kbsy4OmlZSzCnfeUBw4elX9NuwFfjWh92L1MQfnnpOslhM4GaXOHz9UkSTUXvZ3iwS9zRkZkaeR5TSlpsyVxhbfuQ2CC1B0plziFMs+Q5wLHYDcyW9LFfJGp8wemnwotfDG7a1f2gbiIjzRpV0VCWnPRSAzi8QFfP2jr8AbqvyqjVLquTiZLVhMjM9ISZfZeaczYXpTWcnef51yADjbPWJPPm6g/Fc+nh1g0nhy4Khzwql0NCclKrQFkAjndX178BtJCvfflH94n+Ax7gGZNohpefg/QFA==
  template:
    metadata:
      name: dspa-db-password
      namespace: rfp-agent
    type: Opaque
