---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dspa-minio-creds
  namespace: rfp-agent
spec:
  encryptedData:
    root-password: AgAzEsZ7WDgGVEoZx++L8zZGJ61VH15XFcpm8KEn6SzdG5VVDKRRN0P65AuHbOjfl+vQ6dVPDjy0D7ptAEetHp7DVNjdNNQAHbZx0ytO3elrHhigSVXao5AUvYnejgIgD6rlCtzRj2bsE6U4vZCV/QqTsUkxh88JTpsIEpLxDyjyTnXdv/EPQm+ANzertjm1Lq7pevQMD4tguutt8uyBust3LB0dp7RWnJusTohgUmBafsLbJY0TEUcTGNYD/ZpMFXFekvetGIaDPJbD8am8ly89Bgap24q9hFPH0+fry8syYe2exh0N7GhpGLWoWrmfa3WSb7lF9uZ5kxl8cHKxXrJRV/5aBDQu6hZIIla6oXN0uU5yl26X7wEmRWPYoTprbO12AjuZ5rUO5PW7+mQkGdLaEoH1kSTjc+NVhBRlwoznNqEtEm/nqn6GCYCxbjiR3p12bCkFnaWFqZwjDNT4mEhc0z2bSV2xBu1C5SBYBPiBDclcsVEr16K5DI7O4iSjNaMzOVl4n3BoCcyVVsej2S3rII0pFQ3iTBhZOTojcMF20xnPfaSD2MUmmx6TG2xRFIYgeyxi6EfQZL+XAJfen09IlZsUA0ZYXQuDImHDwwE1m9nxJKjxGgd9mDzVvxwZsL7WHDJtDaJyi9pQbTKvilRH544HGMma65Qi4MABNG4ZZ5Czs9Tl1Z07AFcDGi6TfbH6LByrsKW/OFf3nzfhp/iJTVDQ49fxybhzTqmGo/tsWg==
    root-user: AgByI299kBFj0NaTZQJPMsp6ZjIxLHgP3oLH+SfZ3dEOJZxeaZKWSO+lj17Oo3JQZJY1EvTvczZi5TtzIxrtjuJVVcoqBfhNsuGdqS1rc5hBhdwZ5BSn8xICwmp9liRvTYROxpsrBs/ffPQMN6goDpoJ2+xKYr+cBHWiNWRNT22eA1saRnnfmg60Uw9/ZwVT0PENQkNi6H18a5qDTH5964sqAb3VZznluAnb6t0fYpMC05qe4ni0/zzy79k4vEn2mt63TDFoH3S1BiimDjbr9zVzkwrmD3fJu+t7YJJ8fJh0WNSoeivvRxlA7+8O/4Jq8up0+iCbL4MdcVHad7M0GnNDdK3PnMgxN8e4z7GosxImZNgGWwtR+9LYaVGfPy07hekj9GNjLb7+mUJhqz3MpffRSNPYdfC6m8zVCdnsqsb1kDmjEYRCqrBHqABu0Wii7QP6rOQ8iWF5melGJ799XWV0DkpufIWDk7kBT2Rzmef4ISn3IginOjor2pFZ0s/rpQTgoiTj6nPpVutjRLrl52+L5t1uSVuY6gUmJ7s6Wgisr9iln3SeJtHeTPYUCqZc46lZHMK0rY1VZa6KmLhukCfKESzZwOYxQAq0I1v/DBgwnkPeOaH/GN2fyC7wI7eAQFUr3Bl1NaMQzbJDKQLZn6+DgBLxg+WDJaRcuRb6wLtqUkoulRNwD7Qgo0a7PjfRe3QN99cIUj3BTtob
  template:
    metadata:
      name: dspa-minio-creds
      namespace: rfp-agent
    type: Opaque
