---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dspa-minio-creds
  namespace: rfp-agent
spec:
  encryptedData:
    root-password: AgCROl9L8012WnzD32sOFB+igTLefQNlCxj7Qmsxc/LDzliInweiRFRiML0fS79GSg9p2OGCHVboxCGx8ygTjRYCU+9n0rBWQPv1pc6RPLy4IUMGrFHEXtTzvLecwNvnoUwvcofd7DEV3nQP9/DG9iXm/tjFgdYWtKqbVZwmFuxCs9qCRjqOJyVnfwOnbp4H48mUZHHnGhsvV75ysBbroweyl59cuzAVUDnXn0wE/uN4d7Yc42MEnionrgo5JKCMDfXygNJk/p1VsB8AgvpBttX0dnuoIIz63P2JHxQ7BS/D0wZ4JcX0RNFtWl1TP68jOqNtnlTlhF4WhkpnoQwgA5p6/1cO18PS8ncfDmAf8XP/jdPovDQF/jv6Y0TTjmV8nRAH9bqP8bPfXjkZL9dqkHZzQTKSoan4OyHiFathS2Waajv6VvlfMYKHc1n8Gl8hfIv3B2ZsxLtMu1qBRbHcc3PPSVaNpk/HX4Hg90smBSa4lMfcGnubYvZYWo9MoxZH/3IXHeHv9/wZV/1bwHAlBX82xcguMajre6eBTSm6tFSgfEEvNZNg20ZoQNUZ8ZL5g7JXb97y6pB0b/hhBSWjsr+yPbH+S6qcHoplYPxm9OEIdI3an/sdnGo4k2gCOWzPapflnha9eGVHn4TYxWGYCqo4NptSeg2kFuWUpPJfrasvJEpYCiiCv4yrVkVjAex4rcjmEiQ9hn+DMEal/VOJTRx6/b5xJmMAPwNFPcuZALR4/Q==
    root-user: AgCSUtXwdq4cFQ4RGFQ2Ziu6IKnfXfWsB/vq8PJa8rhGpzD1O5Y76ukdfvOjmP854imYLttMvVvDLnGYyMqoAvx7YsP03j2x19D+thfZPcUd7fN5nNKA9IGuPbM4/IA+1pIOtdMb+K7dVd7aP9TcCgOPw/RZgDxAj0Cz0CrDsm8VBoV7qvF10LtVbJOIW/Uv0N45LivyXbDhFou5krp1kb32s6qVrlN6Ua6zxLivMDwufGrM6R2+XjB/On2SS3RDMoJDNCBQntAEJYT8aT8KxmJ1/BpL1DkrPt+UU3wBmGD/xEo5ZmfBK415QuVi7UWaa90rAuYsiOHwTj92RVnN1aHCfCjji2JKQ3E/0cuz8o7XOXXzN5d817vbfvOqV+HqJ/uBteYM3oAf4eEFyHpWeXpglkzUQKakEdOnfAu1Xxu9avxTMZYcIjTjYwtjhs8hubIXmkJGeyZvEU+HSY976NHSxRIVi+aAMzJMXVxiV08LQqaqh7JESyrukc0HcruDUaBjBq0mzkPaEauuK2X4r27Hra9RjIIvIPSYxq185aD83Tcr0aFQfFWQbvr2IbQnOe5XprvhwaBaTDpqnOlMdtvretJUJjOTYqNiUTBcyp1TnOfKmG3bb/hBoFOmyK2a2eG1hJ18/3cmInyBJsjtj/6bMhEygy7BjBVoMi9UPwC5l3n9hpY262cSDuCF07iXieBz8PQ79tCQNfDC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: dspa-minio-creds
      namespace: rfp-agent
    type: Opaque
