---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dspa-db-password
  namespace: rfp-agent
spec:
  encryptedData:
    password: AgANc1vXNMD21KSbYkon8qSBzFoCIfu/AtrAxI9msz6pbMfXjOAySLzTY2rasQTjT8TdueFcFVrZZyuQzc2Y/NSBfsnRaaw3iipdkND7Sfz7Nb/2CqhBlfAuXYp9ad2nA8dX2btghsr6saf8YdB0Ra3CXYlTIYb55CLgG+IsTvhKXqJQlNyAuHBCQlhODVRmayjmeUYwNRvGitk6NNim2niWoFlGyrAkCCOQhTyMGwIJFaN/743X2q66dQputkhZ0sXYd+dw8+ScsigviMl0HIgNpTr4PTsNMkUkLSvA9uWM/r3w83DUPGY/K/KXKHKFWCXiPQG2zW9mTo9aDCR6D/uxqZvzA0t9P6s2GfwcrkIFSAlnIYUkNoR9XSlNc+lSDFb/HsUAZZp5QtZqUmFKb2fDFSL80FbRymDOZVYgvC2x4ZLq5Cd+C5WYfAp8IKyhmyf1QXlYt3yLqfSje4DVRpDaY3xXyR0RRpGPXsy5mn60rFTLI7ZBeXWHxJJZFyCw7/EKmIj4uZosI5o0lwwqBo6MOAvEZo561IAkAwPQXdty3rzVjl7wAn8Wxuf8xZ5tj72K1H4i6m2R2V/m8vYei4FWit2ocz/vquLeG7cRT33DUcF/1FUgvs1AynVFgZWYbjhDRAxE4sdBTA3G83sdHaVtCappBYWqJY2l288/ZCvUyf46RsOj3sMrFlEosVemwESrF0L2K8/0pJ5O5EBWUpktZY2UHCUMDNUJpOngqa552Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: dspa-db-password
      namespace: rfp-agent
    type: Opaque
