---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: evalhub-db-credentials
  namespace: evalhub
spec:
  encryptedData:
    db-url: AgAQe2fn+rWXGD4ed3xyglfr7509fnQRf4DD3rizD49dyes9sgs5M2AVCJv1wxPnLpP5XXUqRZrBsiJB1zjmfp3iM1Qk4WKkrJY2utwwZ87zkvm2tPj4+tv2XscS9Hsymh40Rf5z+eiyep9CXKNg16m70gTReZNaAdUUGaJFuv3x3suCkF9eLbo4/ioiUylhkwBL7v0wXOXpkP75C5NONSqJaTo8G5bzhZHitICFj4+PuW4vT0OeFch67SEVa9wiIRmEmVQK7qKIJvkBgwJYFgDOjWY4cRBm76Z6OktQApP9ymLjE+x/C6MigT4JRUFbAWCEPncd7KupDIzApOPnCFQIYb8jesGu6MAsGfOIpv+YHimySaRMUOsJLWjOHqh5E7+fQcUXc86SgH10G6ATiujlLTVkgWU8TNEJTIX82E4bIvBfD43PAwVSvi8IAT9x4Byo46J76KSZlpY0JlRFghERKmKxUhlzb345ERpCvfW2bMvOsb6a1WV6xAKYMmMAYq6On1y59tNtBLI6A7ZHuUhtc1FjwgpL8tbYAtzF6cE0IiRPsh+ZOTyaeFDsub/M+cOSs6/Itpf51toWwTXwicoNcBD4VRWvdEAEePjjsy8Riy5ttYoMChdfUfaoqUvoQAfzSscnbkU6N5BcUjnS+OFOhcLaog0Rq5c/rB567Hza8Ug48t413xHdjTRiok3rIKZtc9mwK00f2iGNiLxm+MmtskY8EtGatUpZSHXA5k2b9gEBgbD0YLtdI6UvSxmSR+I3SsKp4aJ18LRppaCaiVMLiZJghLN3w1dB1bzW1KnjbywreTAu0Vuts9A2kD+0Jakma+rV2MEKx0U=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: evalhub-db-credentials
      namespace: evalhub
    type: Opaque
