---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eval-gemini-key
  namespace: rfp-agent-eval
spec:
  encryptedData:
    OPENAI_API_KEY: AgAiIE+yHYyXAMtyP0f5MF1HphUXUWQCzuOCkobjudC79Em2MzuwdC7J0dVhZ3jbKVHrDTuYmEL2InImfFvdVbQi3Drq73blaiVjgR1/i3lvWA0cyCb1XI8Doq4teYyE6GuPRt9rU5NjIds1NZPF/PY1k/Z2KDNcFVqTQTyTyezGys9k0wYBQ2xZEHYhFM3Cjxq8amYy1VueecQfUK4vIgO/zkYa7Ee2FMcTe2W7xxmSo24dyXlHQUJ6Ldohud3DjJTVVe2BxWfmtRN6RxVgyp0Z+B4eZJG9By6oypW40y+4nzfTPD4eXQU0oXe5uCz8vFRM1759le5iuVjqlLU3lk9t6PBpN1qFJ8mjGscH//BaBp9EyW8LQK18zVv7Xi32Z/2oodk1LTfpyZwpykASQR1Gt+KLJdt0pXRYCu53RfhiISKdn9Oyy0WkkkcczGGVgHFfAB28p0QU0l7xAgm1ox5zon1h1d1BLwOC+5KsKe6xV/4dMxBmI7aju9D9X3U48EvdrVgoAgRlVoV2YP6TDlH9hvk5bEcZMvaIPlrgvtk+RkoP3DRE9RrNoulDy2ChSOwp1Et1Zt7u/vmvHB/mKex5RZqmsTy11VYtN7Qm28UvEC/RJd9CqtjMpFukLmEjv0/nQC6TozcGTUGAyxLJU48FFKedM8avV9ff5l8HyvdYF3EZu7z8L1cx38XtOvxlf95INF4rhSE9F1XNIGzDVFo+NyhDruuPWDZNpc1Fl4FanLl0pGT3CaE8NBqavYbb3qDng5HTBw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: eval-gemini-key
      namespace: rfp-agent-eval
    type: Opaque
