---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evalhub-llm-judge
  namespace: evalhub
spec:
  encryptedData:
    api-key: AgBvfWoxGFLJQLhLHm7jUqd2T3z3LmSoiIIZPiYmUMRkXfgPKJ/XajXXPCsqT2HO3gkJSSiuax7af5U6imQLzr3aiDZCq52gqFTgON4YwLC7Y+HH+ZMXhXcd3UA5PqDN861bUG12RFgbThpmJTKMrSv+WBRY8qRvb8yVzurJXK2igF3xaGWQfcG+djNBOVlnoM7Hh/dJbjkC6Zw0fbPKxfSNo2qjiUzYwWQs468aWyQnFAaFODryxYcgwjSCi/zrLJmUG1y1frKav1GcmD1WO2VgZ+ygkbyfB0We3VyRQlRxkKRDN0rTHghthP8HRijyjkg+eoJ9HqDeNuERaOyPcG7jN4jnHRBDammSEaZWeR3IzfrWMIcn6FtuHj8IvNdJSD45VHZQBK1hSLJIQKDub+2yPhwApwHSOXVeS3e5fzuN3S0MeBuXft7058nflv3+f1oK5mU7hNZxSc7mBnX7rnK/dI9cFfEembbkXSNHiNqmpod18IHNbJFqGYbfMjqAxzCvFU+pnMwvNJJY1+AIAmU9uUC7+Wgqjyf4aCLFnVcOQslVsiVNg1MbWvf7gQ6sdt/zskRPon0xL90FNb6aVHYHCX10mu017ph+TBXTiF7JwqP0KX2SvmTo/XeGC0rY4xQ/+AbIGe4NWamFqyL/jNcOelh4i3PV67DORWpshvsR4OhisCf9IdbXA/bmAqbzzBhEhT5YU/9azOBIZ7f1gP2RzsLwoPBZsBnVdVVETxZq1nF43A23ptilkpTrI2Idwch5lQ0agA==
  template:
    metadata:
      name: evalhub-llm-judge
      namespace: evalhub
    type: Opaque
