---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evalhub-db-credentials
  namespace: evalhub
spec:
  encryptedData:
    db-url: AgAoZmqQ+OIIEtFyQMtzNqSabQco5a32X1JcNSo84/x6md5Y+Jn9Z+e1DXi7WFwloIevZ0DRjxzTcEQs1NnvrQabF0xPHcZFm2bRWh1/LZcU2bvARme71g1ZaXxCRn5zlIsBvJql3UREgJpu3U7zDTFqoklR0CnCGbwroT/GSw668Kl8qL9EtBIpbN9EY96iMXSXGLSAriQhZTAzvwWmW0bX5LzFkVbpMFk2WC1/az5BiJwS6hkdOM8mVDXBYlQA1U8PjOfRIvMvmq4H710eGCAFbsBua4s/u57ZCJSLdzDUViptX0i1VeEf5fG1e2hi47AQtTXnd2oF02cCBRPOevtAThrxwZwQk9RxKF5z1kb5Zz7wrhxCqXC5qwRX1zIe4vw6hOtzHAIv378Db4GOn5yPe8GvJXQlbUXaXmbGeQFwZIanM+Zmi00rsYO9XuL5UHbjGv6/dbGWJetjwG+2mruMFCZRFDrR/4ZKRCA2joTc47AcDMImgeNgU3KjrJDwPRhAXLqB2z1RrCtZLVsBl1pb6sIDYiZnd0vU/UHJg4c1FKsrlGOQY2Rs7qYi2zwIhiKnbTger1S2cA2EHNLn1WgBznQSnfY88boTbIxO9NXAflN9pRnMfZJrub9lDseP8XBBXWbmAtX8Nc4asiG2yPQRQtqO3qT9BTGWh+WLra/6JttmHiuksVKi02kUli5X2kJyovWkaoSwAgQhhpLeqrM1KaiM/EM3t8yk8icNv2Cky3xvqji7xRo+XsDqkcz2l8dcCU8SESTkkG0dbj2Dx0b/6fVYhJ6Ivof2c8TDnv/85/vXc9wL+isxGkCjL4C5yihOhSNgxInwFuE=
  template:
    metadata:
      name: evalhub-db-credentials
      namespace: evalhub
    type: Opaque
