---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: evalhub-db-password
  namespace: evalhub
spec:
  encryptedData:
    password: AgBeMaefVqeMteIQRbmHDcZSESdV4UiGRUdawsL6A9n/giNDz8Gh9RLer5c6hyTPfeq/PeALzyU0WwQ0Kn61yN2dIPPluF2HXZfRMw4X80RGAGIMSpY0DPgN3x4PCrzbUXhCbklmE9WMjvKhuzVLNC2NYTYdDoR2KfIBI8ML49ExCYSGf1vzWeEYG1RP4lA6Tp5K0Tv9JjpTfltto0Vy08DF6IxY1bODaLJQT9nTu6pFPpqYh1gt7IK7/rcf3+fT2NKwhS/zETWmz07oX2KObtUC1ICamfDYWAOFlEtPpoQ4gZbvZeWND69jSX0G/QOE4D2f68heTza/Eouo+LoDuBaZARbh5blI0HGxVCF4aq/SmJCsJa0gC45GnQbyy1c1qkkglAnQ/LMI8r0gM+Y1Bf4xHrIjge1DDEt0SiDda4XNlH5f5IXilm/J4+eo3rNYHEtk4iJ88uPw7NMBHH4YuViKv235n24cCbp57AAA6Q1FZ8gdZa5UfczlCUe/JHMI0R2YqmTbBIHg7rlvMLfn6g3ICYUVmAryhsDN52ibiguxt4U7zyfvVfwLsdPYZ8YWNOulVjiNBajyYE7EwyetE677hyk9RCA9TCY8XDgXu5ieWf62qq31kaARJ8YfM+JhJmFeGHSFWbipKhc66IvSzUFQ4Vxx2CYK5g6Tk7MpbR/NxU2AOWQFG5If+OHy3Ha/9j3zjVwet2+YVs1sM72vK76xTEj4RLFuNmUmMku34uUbnQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: evalhub-db-password
      namespace: evalhub
    type: Opaque
