---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: evalhub-llm-judge
  namespace: evalhub
spec:
  encryptedData:
    api-key: AgAOmSFk40bfUvbUyP3pyXJWs6TWARjHGIyEB309PO1dGec9K1FZxYW36tpPZZBO7W4mvMNtlVh/HU9Ssehy97dsLwi8x29/BQ3Myyp/TmwgZGLPEjM4pVdVV9pL2pcnQTLxzE0fZVvCFTCUCAaUlmS7IC0W8iLSEEpSGCWqBWLpel0osKQDSJtybKQyY9bl2Uykf7GoI/ci8yHE5UpwHvufsFqIhzHonF2c8+TIon1WGUnzTvobF1ht3vnDygi5Sa+jmacYluYTMvekfEH7ttrrmRLdjfljIyDyTvZasEGqqjLXqSV+7aR688+DYIFqIt9JkcCz5aWcwO0a5hwEocwqgd/lW752NAhSjyXovnKL5TGlpQMgbWf0E3vcrPDKI2go5bwVoKeUsFLi33ETmzcRFSX4PkN68WBZYgY+K1TBWG9VZAqNlGjItY8EyBB/ccZ4aVEPB0cmrBeFqVPXRt81LYktVuBuCRw9CtKiQlLoBi9tbNCVQONFswtzJZzvp5ZGsTL1VHN3eGqfaAt3pD6pLVCOpU7su4eW45RJzvzfmY23PsvXpLZsDSeR8ypj+YcqoY5iKf0qycNWj1S9PZtWd1aDi1prbUMLMwOtRHWqfnp/ZKYEwiaHY8AqaYKBjlHg0dNsomTis1bHXO31fNtUKktZYNkmotBqM6fFXRJo0EIMs6d2KDlJ2qKDGRy/GiLpvuWM+wX0Xe+9B6vPQ5xT0xl7SSntJwAY+9oGCXiCVkaTKqbAd6kbXnlTJEeIvNPTuuxi/g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: evalhub-llm-judge
      namespace: evalhub
    type: Opaque
