---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eval-gemini-key
  namespace: rfp-agent-eval
spec:
  encryptedData:
    OPENAI_API_KEY: AgASlpoeWylS52FKHW7xvj9BzM7+AHJMMOeEEoypc0PU1+WHyJW1qDta4IB16V0WSjYtshtRIsVdAHPjBh1zCzsgJJViloRn7kMGjtiybF7qNHxjjYNYRj4CjTbZr+YXR6kI2gbRtlph0UVPJgE7fWSb+P9F1fCruIpbwhZWzy5T52VDy6hkKfYJuwds+3vI6/5yHDOnI9fCOsqZYLrOkumWA5ayQ4oEaXQ5S1VTs02dZXUCFPoVSTjItGMpcRrtbDZchZAZFeDdq8g9YC2bY9Lz1IaDeqsFgTYhmdFs/7X8513IhOM5706vRHVL1+md5czmoaHqXJJ+qxkTN58FRXMhM27ctjJga3X9j8DzDU0QFroZ6x2ax1i8StwTI484DLIruAk2POjJ7uFgz3qxGL0Gzy8Vir9IMhxae2LFb49yYLibDSmbTvx0eXN/Dv6UWY96Z0ykHgInjCTKBHDcepd4VQCg7laeTOnwacZbpFqtCMzndHpS5ih/lvfHESGf9ou05wnvoQ9Okd8TAxhOr5KnDUzgMFHiskosQWjze1JVQamAOqGZ2XkJ/NfSYevLc68J3xR7QwQnlens0QPC2RxBdOyQdFdgMyBUcbcX/Bj5pTT8Tz8+5ji6Vo6sdW9QQTprQE1YN+g59CX3bbmVpUzfvD+liq/yiouyCmnPu9JiaA59aSfXvNMouy9AfEN8jfFHKEMKVRmjTN40sVrt2/kWxaLflLwp47wEiPxu7uWa05zZfKADb6pXYLKEOiE1wEqqD2QxnA==
  template:
    metadata:
      name: eval-gemini-key
      namespace: rfp-agent-eval
    type: Opaque
