---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evalhub-db-password
  namespace: evalhub
spec:
  encryptedData:
    password: AgA97wRGVk+q6qoaauLV9KHFp88iVjcqW9qPeAUafXZS5HUEPrk0N0a/ZZg8Y4wSJoeKCXnwwmSXmqILbEFgmsBO9dKjaK5osdompvO+WtzbubB90PCyWzshL5WRWecwVLB6E/2tYh8NSqjQmGPkeIKhyTIgT6fcK8C/wKcEali9CVMiGmGnAKUFM0bBQ1x+D39Vhy778I0mF18bSbeLZ/I2fzP+xujOAP7zm9lFMeA7xn+iaFq1qKQtIlHuJk6bIII1JU8o2Cj2WW/NkCF8ef4ULOLfQB2fvcOtOzMqjRvxVjZLrck4f3HHuxpBluQsVFO8H0HN10jXApwJO24YNWkqTkFIa4Vbcx0wqhFKbiGRvHEC2V0h3z9XqaTU4comIn7XWooOJWGk1XAEZn/Kg/V9tMdcrcdyski2P5BxSuyqMkVqknFN4TpAozKESBWTUJYixaQGgWNheuCfoHhEUBpvxfBp+MbMEF4T4x10UXJuTmEQX3ca0brUs3hRThZ19An5FOqd1gGHF2n9+RKVnf4mk3Yl6UEVpWdO4NU+ecdPcY12qcOlzyUUaJkJ70u6151N2IUyYGJtencvN3L9pjiys47odwDu9q+BXi+Kov0HAdpOHIVFn05+/kV+9bRmNwXfy0Txf1flegeiLBbg8uMadRC/Bb5Wf9RG/H6KNLC/JFZqJuEQ3w/C//H5w7480Z96cdrBnjs0B5rIMu3W60VjeooFwjGDYe9spNEoBFt6Gg==
  template:
    metadata:
      name: evalhub-db-password
      namespace: evalhub
    type: Opaque
