---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-clone-github
  namespace: rfp-agent-eval
spec:
  encryptedData:
    token: AgAPK42sNF8+ErLn5FE177VPp/M4mYslSWfYxMZ3eLUmPZfnmOWF1Z9nuJMNCyrYqdWdHc97t9oym6k9FbNFhO8aGSKo48/9bVw4FX++r+tOxtL7eU+9+bwh+H43+D5PBlNlEk+iP9FDxkPL8xSjgJi3v3Ha2HxzRj9XG5+AwvNC9atigJlSaKR6kT5vZMwURggga4q6rBbCMaUZWumnFH1KGJGEO3+R70Y7Ek52DHi59rtepeyaCWgMhT5jiX843X7QfOV52MrUoiBEKfoncryu3yxQ1Z83q0zWQoF1TpGB9oCtBnGCjAJepjGCjWk3I8Il29Li9qIWzIz9uUQ/9YFoayCQdPWeFkgsU4LaE8+xH/OgIgjmjiHkfkB2JpuogWY7/IosP6jLMHX+Zc9ge0VAmMASsGT3j4XvHGVwa8y9TcNgRf1tD3IEuD6NAOs7pVF+t1HPlrA0m5ujtCaispib5FH03NG+cNvDRGpyhWAW+D1DanzskTrW09eQZj4/gZ8otR5mXBwrM05Sa6C29Q2fCY0dqxUpgIOteqHofuyYtDGynyGKogwVT/funZBYVj9utZTNpo8IEuCe4n78hmrBhjHVW3AWAw8boVxYyj39OTx+F7noURckitU+9xFWyDxKkgUJyEPX3eBN/m6TT7qkPfRLrzOeed9oN8gh6rI7PzsORM3esCOn3FscIAch/ioqJRJPQEn0pqxQlp37lfaQ0AXjUULbXcWvgEdjg6/KWajaxSJGRd7R
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: git-clone-github
      namespace: rfp-agent-eval
    type: Opaque
