---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-clone-github
  namespace: rfp-agent-eval
spec:
  encryptedData:
    token: AgCUoH1lNBo1PVlpKbzF0PTFxnC/2YH/ciL3vwEshvVEBP4gm2twoDbgGmMF3k+/gL0sMgpXowVN3uW3SoTxUmCxkrAz+DGQwtMH/1+zAVQ1NmveNOc9MGfC65CZfhopfizeeEQglQ9tbS6s/JjplINcY6gcz5DrBL5zll+kreT4XKg1SUgGh+x/HJradHG+43lox9BEPoo6SpqyT+opJ/wJWmb2NqQL9ZsLDE2UgXZognixozgi99KD+x/lrc4+LmY7F0WORXEa6X+La5dDG3W4weiY80EjhPbVtAQB+9F7bj7Y6MPKAAuw9qrEv7vCo/PGkBWyCq0NC3OJH87nrwnXvHokgaIcQyZrVHg6Bd5zQXSQPLY8kIfi/Wbpx+6zmt0AFgy1aW32Xd1GaYpTaeGOm5R9po0EU4zRUdcvTM4TosTxU/fMTZXPbVwCZHmBTFwVzMqRF6BNhmm9FuvGRRkP4BfJFAMTECvRI/C4WonFAgRABjR5yBsDpQtGYTJAoM46u9ryIe0SNdM0dlkTE6w+kP6NTtP5Kp2AE8kOfbVXTYGTaoFbX5iDerbPUCqkmUD3WrDGFvJt94JL3qM0cGwv+4Wq9I7sRMfvF/FH5TDdFvH1e3CkrH+Y+BATHc2DWMVfXNR01AYbMQ5k+HZfIpcZz+t1C+q17T7wOQalB8mRVuskEM/FJKrv9lEMkqhtjYqS2EXoG4KbwoO61C+InmOxREbxmo/93t8OXKk6YnHSiQCNcZxIu0Uj
  template:
    metadata:
      name: git-clone-github
      namespace: rfp-agent-eval
    type: Opaque
