---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-clone-github
  namespace: rfp-agent
spec:
  encryptedData:
    token: AgCVGTEQJlV5RFSoEn2eaEYoZ0xXNMDkZp+8tDXgHHecwrrRlBSq99lqmKLl4LnA4+DeMRAYhXhT+5kiONlC6Uw2R3M5uGAymDHXIXlx+fvxEWXJ+m3Ml8KRf1JmI36YdhOqyvSF5aOtM8n49ighP1H+b4VMJWKZyeVhhfCCfmo0FAWG4CIwhd80cvSQrILcf8EFYI6BGOzEu99zL8aPiLib9sGvM/h4jVCD0kdtD5FDNOd5PWyvIKVr8g+DQlIIwKkty3/ArGd7fZfUkgF1ebssoa/0syfJ+6wKQ+tmWgICxLw3h6Tuyw8+is7P2LID/ioib0xM3OAfFWdJVfrrKx2J9vqhLbVtH+d2RkTDzFcW0vuBUhYWcTdBbWwKvp+MyYTPqgmCDO+KT9WZ4MBjwbGsdXPd3AsvtpAbEqeGQrPfu11M2Efa1NkGTixvZDdhETg0ZHP568XjslWYG2HiHWzUNl43dTn7TEsZBKDlUxs0N13yXQkgFR60TRE7xDByRmikePhH/lC+8EcPH2GNSsDAWGrNnXWXcF2Ah4ldSX3w8PwrcYSDPcbDbp6qx8vTcRFwtjWMchVX40XJJ2Asz9qEwIrqewc47Xz12cM9decn0LJcKaH7CPnjpE84T9qXVYlipDcd0sahhMrkKLufb8cEFe74qpiqDotp45Na9K+sXoSwS7LRXuXE+vMO2KUvuoyh9+MgePHnFzdtlTuiE2zRyCP3486OGUt36lVa2xCQIGpCk2+bGhCX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: git-clone-github
      namespace: rfp-agent
    type: Opaque
