---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-clone-github
  namespace: rfp-agent
spec:
  encryptedData:
    token: AgAXzsSHdl00QhOURpMHweJmPj/CqEKs2cVzgr6zy4Jt7Vuo0loqpZRrF/Bt2/Kmz2nBz5vb5JhYva8FMwLWs4VB1JsHSwERdpJ2OXw1TIckVQcvDBYXeaaY6mTyraH9lQafAim2p3CdSmAfT1Ri/C0rDac3RyL2iZhN1j6yXCW3j1GgIXB7/KrqyxLXGhI/CVaky/IhUAmb2cT+Uykd1r0iQVTbkNcEDcAH1S5GTPeL+pUA8dHNRz2KA+n93+X3//O8A9BT3Rq3sbp7TOAd0eN4QY2PikdepeBmeIHrNBBix2MaSGF1hJi/qiGlFkm4pPejwtgtbD3vz6Vc9mvvrMkJch0DJesapXJuHjEZphFMnd7iXNAX7r6KcP61PoWKHbwwwGPHtNr4h4X59B5kpCfg3Axzt58bdSjUPVyRLFoVcJG8KXHm+6pfdc63ztW806f9mL+fk7+osvRy708fGRnB890g9rxAgRXWo9PdniS+QQWzZGyNSgth6+0eSkJKxK7WZblFDn0wp4C5BDFFgpEU76WDkTGeCQx/AgZj0qemis2z5e9Ie2UCss/YzGAA+1u6JChPxVfKx8x0Wmm6XOLZ+AeKk1lYn/h0x8d2/k15Ip2UFcE7kJrn2/WQbDSbU/qJVlzM02zofmSD7pV3JtUkOjTpPZ0sGLCFj78Y9uz79yuFUMBmYBNzNPb07YS4rRw/pIhcc0T19PdZfkudq/T9VH2IuAcmwaW8BWE0KjxiGyhK9Yu+av96
  template:
    metadata:
      name: git-clone-github
      namespace: rfp-agent
    type: Opaque
