---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: milvus-secret
  namespace: milvus
spec:
  encryptedData:
    root-password: AgBzVhVO/5dybP//DAhsJBgiSfa/NPLG+3g/13Ob47Gm0a7oGEX2zuuM1EjrTj1F2KRPH5JUtUO24kwVy+2OWl4FzQJehTRGH7H8g5EhnZGSbHozqul+XNSbWso9NdIYqph9FPM8rALNt6d9ylImgazBSiH4py5q61RWRRvaLpc17Cp+Aj4PL3ntK509owTNQnVOunSw077JawcoI/0DuLhS4ZOsaWTvEbtaTIn7taRUXegPcjyDjL3PBEzgD/ASwBHl34zT/C+ZhYn+BOQZY03291AogkkpIEemJdR+lmVGeSM9Ducxug/Q/2BFwf6llLxw6QJL6sVrw4+YxWPNYnxlMTSKFABLEss0ywf4BO412Mqg/HQJgcvizIdwxLLjYZyd9/4zH6MIUELzshcIScIIj0ioV+A/T3/pM0CDtVM7H7+LBtXkwHAeMQRbmRHle+RU3cYRlsT1ZxZX84J/Z4u2ZIV9acdFmTyH37W0xJhEhiesgbkHI15WXsR7qzWzmIwX01UXKoeiHTLpDKO1p4hipuj1DPvCEJe69Zz6z6PJAc/OoOw0Hcq/k276+Qy5KkAQIh0X/JuniLFG+fIKiQjPwjtSQVJym4ptf/eG121rBN3n0VVNyzfcuMpNSY535Ktinc5KvxdJPPpd9ipeQ/vd+kt0FS+NDpqR1tQzObIz2DP6cvu2h/rH+AcYppUH7odjXaH3XPWKiZ8upCr53s1KJRHxXNQiidsFigX1eWaY1A==
  template:
    metadata:
      name: milvus-secret
      namespace: milvus
    type: Opaque
