---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: milvus-secret
  namespace: milvus
spec:
  encryptedData:
    root-password: AgA6JrsA/sf0cXMzoaqhdBtdQld3saUQI1X7bFXHA5fUgT7PF8Fb4B2vayRzsmY6hVEsN2kh8Ro5oghSekd9ivMzP1etqw/jl/AAR0xsMRFgEg8fRx7ZpwmaYUoVCvde812fik2KJmqeVW4Nv6Y1XQul13stCWnc3mxAAMuD8hlk71OFbCQUjWYt/JYrL7LPEr1lm7a94gUsnEVTkTLQVjHq43GeaY+pC7tdYCyqsXWmqGGdab1/3/+7J2dPVBXInbcCQfPSaYaa18nQOVYo1l7nkC/bv+b1mAoCE7OGI5RD2tb06T/2rGKc9oSPFTFTO0581ix3OKaAkg3ddp0+zq7OiHKNo3wz1hkBEekBLuRWlPvoa2ApCv+/FoeObLaO/0M2LlG/GKs1IITDpBUQBDLs0DfKc7Ysg7DnVRGswD7CqIXZiWeXwrBkwV1Zvdqn0PVaM/mVJgpXor6smKtQZQ88rqz51gw1l+SuELHRzjBTpCcXz2qBGOuyllhrmfDi0hpOOLlkENBBsyp8fxUxN9TzCtc28EP+6t6u8CWEs8tTcEgne8iEfuw12bI9ejTJrK8kWp8Kyf03Gnqly2TCw+Vmc4RFlojgxyk1xITQalrEVPrYTVn9rbxTchTfI5y9EE5W7rbMBHB7ivUwwNkoR5gL7YG+450HJ2FzQEIQH+5Bm2UiDKiMFas3mlivsPGbEOoyhzU6wPFD2aPqcVG72uHKITIGtn16ZTW+3bB9qV9sDg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: milvus-secret
      namespace: milvus
    type: Opaque
