---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    root-password: AgChZIjJvBozkCn2dhFNzDd7SvMlqdfmKilOkbCd+8D5V4cD6TIwYk2IKkD50Vw8MHNorLNC3TSpvg46uGx/cVpBPMr91iN6583KwBsu6+hJtrPHznfLGq13GgaLvfTx3hZB+jvIAoK5mIkHj3v87UI9IbQd6z9C5LWEArccGvxQJy/PLIsn3Wc/FjSqxQ7eXt/1w4bS3R8xZ/LGUl2mGCbzwxrlKmpHMM8mU8ik+Lc1T3UlQEMJ59byfGwcj6u0Gq6XFAn4U/ZDAJ3U0Al9EI7f2LrJhrj57Fzu7LuBI4P1AT6k2uR6XCfhc2z7b5swvcP7KlIkkopq9Lupr8WjfcT1DPBqWw3LaR0tH0kR/S1zDjBbmUdXonKkT7w6VTBCbjcp/XWo1C+T4KCpmvhSu3xMgL8yuIqi9Wab4ZCcrJ0bVMMEARVgXFxffjAldZPsX4NECGIQHLBJYgW5k/nzlCgZyJbp75gffKHJDiO4CY0ergNXF0FHmp4pVTHYWFqXnAS4M1/z0IGpVR8VoiKXaGsvyJC3eO92VTr7/fyyzTty3emXRbtcxk0c29f/42YyuBgMjuRqSokqJ8YkJYMBmcbaxU3Aq3mSV/zmo6nYlq7Ao22Kw3ZPDv5yu1tjQ9pbI9G3Qp5oTIelp62VGmZiiNWxlFa5kWnybs3WWW0t4FLVjlikLo4VefHVrF86QSiITu2n72/NflZ98m6cbbfFnsyfEAvr0TmLMhlBsqwamBW3/A==
    root-user: AgChstg+L7UTrB9IOZc2p2YKIepSnbuLldTyLT+3bHzSKJMbU/Rs7ywMMhC8+1iQyP+4tYRf9f/iOKyHVsLhpQG9O36Q/PU/YLG1fe7I5LGhDuqNcp59UIPNo5KS+kUEXRhcdg9CuJbPCjSS2rlWvK4pFulIplNy1R4/dwU2xK0v2+6RUb4uGQbvGVopmZYG80I19LFtvdN3GqLAq/FoVIOSKYJr+lN/a0mba6MSGGNit0EqBQdzagoBpqR5QQr6J2MQ3YoX0Lto8iys8wDr+WKDToMf1qQG7AMzBMvCCNZcUVDffsvYquUz79uyqIkcT2tz/KHLiMNoCZlsGO7ajNKekoc9trG8gRzUdgBmadK5tDYf5G6qYBWQYLZIxVjcJos6zpdYCYSrVCg+LC2nMTHTNBaMx7NdS2pfNFzZZ7GRjfA4pjrTTVMqwwCUqF92UVBIR39npp9srUgY74lNOm+D+hR9MBQ+11rCekhaZCqdxBdpeNa38hjnOJEhTXDIx9L5UWLz8oCjlYu5vO2qpXxQKYvwjC6cFHcTH1KUKMh84klwUwrKSec0TEQXKvfbCJsXfyQnLxuZTZ4FrO93FBmlTvh0oIb1X8NdN3r3cHME+QPSsWRRLCYFj1uW6jKun6rMTQoGgesH7iuqURa+NSL6Q9Z6P6HGtuxTNHXwZFDJrwrwer/S08kyyJTo8W1EQeVTK1GpILCP41n1
  template:
    metadata:
      name: minio-credentials
      namespace: minio
    type: Opaque
