---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    root-password: AgCX1k3UzPP2BesHbi5BqYS9Z/dJEHEE47sRtGvRguASNL9WwYgkNPc44eSpt7/zLKjP3MzATAj7X/vaL7B26x6gH8yWnI8MpWRdq60e5ku3uLxsCYwD7EqGUMtxRxgyox0iLQ3JgWVwuB4+c7tT3zeSoJF0yx3HPvTo9/8E+R361Sx5epspbEp1Q1pGq/B6Qe4FxT7e1UlUGHOZVBEnO3tx/lv0VooNELrpsBPiY6k62GghgvpM3/grAXMS6AoRzgcwdWM/ljTgRK+SiBk+Wje1cx2k8FBo+51JumERLMdkLZ79acdl9dDC//DSZXnNxIWIve6YV6VwQlZLgFu3sQJTilsXt46ywzhCkbu7xZUbj+nsBisrMUBKM+VSzfHinJQJ4Aa3fe0YQO+lA7OaHF3c5SBZGtA+h+WzCv3qhe30QNCNW2qFf25ijI5WHUmmVnWVKA3IYrhSqGR805ofp2RgiJLZrSucndEeEBIgwtSsZObAF0ooSXDcv8OYMASGp1NFrIEFNi6AQIscGKVgy5hSysgSkOEnZ/5bnmcbxQxGaXpyg35haXe2zLc7XoRGdQ4nE50DteAtYNfsXfnJ0UAuA05Vhoz2tOvr/ypLyNT9SrwUT/g5pQGewW6kBLSRmo1F5hb1OW5GXA3/Rrc9gIiPb9wIJx3Bhy66GVX5QjJWihSwkxVE5IzejAt/80Y+jiGpKdCsmb1BDio0/7C7Z3I37J9YqqPQh161F+WtMF1Osg==
    root-user: AgBHsbvBtqYIKxqoOSIBeGDNHkRJ+rBHShWhxn5JnB33ZvlT0rPFIPyt+QKU3D+PzoARRiniNkFtxPh53yCmFnyMjFfTvpk39fLZtfnFhMNtVpB44EFQ+kZnfPE40mhC+rE0SfPimcuPBOGsVR1ojS9fdHhohJcKZWa0SvWGQEfKG+nv7zZDUYETC9E1Z928F+/9prX0joD9m2QijiYRssavdlyH6ouOX19qK81G86KxiajVchlCLHAEwCz1C/v9976k+H4VUro52NSFPEjpOboWrgmA/oe74TZhayjb+r12oFdEGUat85bCbnzADA7LfJpJ+0rcQEnP2/czNbovzPIE+OGGBTINnm08NgGWAEqA6psdjh3aUvSHkSWeGC9Ny+CoyFqclYSEwHjTUbwB3dBEf9dNRAIZwfFjLGswKvJsJ4kwW/SC51XJKApRONaH4tMEUiauIVCInyZ5Y5+tXD5BPDq+FP4ZKENVR6tcM7zohGzkki1bZVMjVVuID4mJAohLLAz6JTbPieHpvUjMKM+7J8KfOQWHiy+nJj0actxamvzcC50cpr2pwgFfgLJ9vWvVIvwwkvQVBopEJ5vt02dcBHcb7fgFrXeHYyJMEj4G/x/94q8JPjcAHaHvRwbaY8iL2zzAVgTFZSIYEe6rYHzySb07QENDNEWcByBcptkl8MDX6BYpmioavAQuR9EAU1qfPvnQSOttEN7/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
    type: Opaque
