---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-providers
  namespace: open-webui
spec:
  encryptedData:
    OPENAI_API_KEYS: AgAmlsxzbZP68NMaKPiVv6yGItKnOcy87RbEa7aFRzcqvQJ6AJj5ydBs/jL8lWFgCgsRSuE3yISn1QIlHF+ZVaC3e0RAcT4K2dOJfbrOWdbrqF2Wp8Q3tbrqlXN4E3I6edzG/IrKt+BveMB43Rf5G76dgU0hQ0AKLT8dcTI8sJJNPlKElvlvfa8ZQaQcnY3ABFRh6o5WxOfmM8PEYaPCAoo0pF+PeiCHaS0YKMAn5FrMLfWvrNGyiB/nFYKxFADcAVTppafwXluZQvgn9Mz3EMlHqUEFboRpY4YkI4oqVEKFG1J2N52uKTJsEx7FdSpNhu/eSMOAvZ0Ye81u2tWAScD6aaArvdZir46acTb2hD/PL/LeaJ21jB8dzB9yK2CuKVpmWdh/kclSAlBNBs8hYLg01QhKz0arzWUZAZY05cWyV5dbJkD9i2bHPABT1nPZj1kBczfiNQTO//BT7NdksDNOE/LjuV2KJUbexE0iW6pGNVFPaQ7WQhHd1IkYUXTCM/0/DQWbiofmj8ZD1si+yoN5aDu71MTpX2Xt6Hh4DF2bE0+vBA6Ad37eJSZufkY6tAvgp8CcduXhvKqYQ5r3BkItNfU4ogL43/iHqFBCoggTLxcl53quT4Jg0E3kVGt/jUZAj9xunr5B8qnIrI/g314dzy6FOyMZ82+31fg8IG38FYOCKH1skwKKDu4hFAMVVGH4r833ecmHso4IZ3ZDwwq8ups6fCuBhEOv3A2R2WkS8Yf+7cNM5fJhM3Qh2m4sNMV8BB75Z0og931VmyyOTCNAAWI4MDHOd4atauJpr/QfDkrFIGANnyhFAlSOI65cudiTwiH4OQXH5jNuAG/y89qK2yETBBt8nVOJ0I0XcIFxfKPEFv2sx9Ia1PoxoEnH24OcgHd59RrmjdDdG6xYqPbCyBQpXg==
    WEBUI_SECRET_KEY: AgAyNIV9WAw1U0bhH+4suyRpQPf3jpfT1JGcBWTCw2FiRTZamR/33hBC6LLPWmHmfZPc/z3OOaC6/8l++6c6gfIYgZfPysz2WBbq94aUXm4H1NfoGhkE0rcFHDUeIpM4JdP0IfH7F9kRQoayZF3KVSUKddLSOKF8vNq3rphGTaqSV25IYkI9xHkjV3T/0NQhSpmYnNAr5guWzb+kHW8SR6kcKUvJHektPyApbK7x2Nb3nNrG9AUVdjtJcQTgp0J0rvOvthmj7aGZCRlmKNuSquc/KvZ+gV5ugk62sS+xdVjOBfhSb14wt26evlITx1nmoXMM7pN4tgU8yY3hhoNHiI/RQH6/orA5JyztD5qjWt6VcUmAurCfoHFDYMiJT1OBORq87hr7mDLP1cpaxbFvnwiz9MqYa/q2Vzb+26z/Y2Kf/GfSh7MLsXlFjZv08/HiUD1epdIHc75khXlHEi4XIX19tiwgHlNPvy6rWgc8hKcY7kBfSjY/Ro29MtjJqQwlTY/FsOoebcDy581o0Rbi3UsFltjmEkyX5lDgf+vNyTgR5cRIM0gkt5nvfD29BvtxhNjTL0jOQYh2sr0ISLFFTYeSXY5iFdMnWjjbfXLjwqJBrFydnNFds/HLB4Mk+k4mDbxLeGengRSn7pSdFPSRYR1lMxjxe5/vYWpAGhdL+qIKUsTQTq34KOYdS/9xaiZnpRxv8kHvxGzdtcRF7+bXFZkH1OiKyRsTG8yJ/WWApyXHuDR3KpbrHZRAOLpI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: open-webui-providers
      namespace: open-webui
    type: Opaque
