---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-rbrhssa
  namespace: openshift-mcp-server
spec:
  encryptedData:
    .dockerconfigjson: AgBoJhZCvra7l8aZBusLzi9JsKkf2Akbz/1jzhAGQU5q00caLQY0K9h+bmBrNamYwr0pxoQqbu9F0CYZozEusJ4lSc6uqPLn2ZZhxc9XP/pMgllwHiX7jGlbWGHdZgWdmvsUTHoyy/QfjPuDV51y/O8Rd9/G58IzTswB+TjrjOsmMQW3g5f0QB49eMPTI88KMywCv1a8TbuwsAkbmk9TFozNhnBZULBUqaClAfmdyGE67WLZFL15H3dNoONQJwasGTONxJ4o6sFQbXwGeblb54QZLvWgP/LhT7TVJoJHjFWKbx4uuS8AMaDUpA3e9jD3bq2Riagsav0Dx7JPCtU744NPj45btTidPjFQ8QMJ4HkzKQI+8ye55eecqGtR9LOz7but8MPVc4IS08kEbKeLAcPHMbUpkeF7b3lIYerBu75y6OjUIfRNIOl7rnuA/TQ4hcc3CgG6x3TSI2uI7rLJcNWs1MBNSON/JS2iz4CllR6ym88vy0BWI5skgKDhamqEZuDfNSliJWOfIcb1JiWxwU6Fi/U652UPzcfqUu76jwOqig37I5W8WMux1SqMBz2xVyVRxHDz2PoULdu4cFQFYBOj0VMKrOZngcI/XDs8Hh52sVqnTGUHxD1/BXDKW+RtJrJlhDbiADpLlOJP8XWAEprjK8d93wjjUrxBD2jlEMjbmUDZUkDJxRmLoqqsk5pA0Il2f5LPxy8iA1tKDJWDAo78m8dBirKc06Tn+TEPR+gP5v3Z7ocd1tTV6fNnoZs193Doxj1KrA1Eny2L6ig5fDq4YIPXaT6FqSL8n8cNtaRQvh+H32HH5lq633MpeTAKpNM59chawBO7IpYXaOAPad4KWcUIuvatR62ZLAP73yflbUTv
  template:
    metadata:
      name: quay-rbrhssa
      namespace: openshift-mcp-server
    type: kubernetes.io/dockerconfigjson
