---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maas-db-config
  namespace: redhat-ai-gateway-infra
spec:
  encryptedData:
    DB_CONNECTION_URL: AgCSf3syH9sVsa6lDFlrSPliJWcJOGDCf5gib7SADqG6Q95StPLLg19dHXOhr4bFDfzrIx14SAUfFlFZCV8ipKZ0G1qAhqbEeOQuCTs25ArMyFWndP5oOOIDsvNVrWYAOVRv447az/AMVt8YZO9NI9gPrc4uX9SmpxOzA/e/98Kl/KS9JXd3jOPLaYsIDh+8rvITW/uAH+Plrzea9p7nFVjvnP40bftkLtHCitpn46SPsapxNNngNLq2zY4PLViQhZNx9FEcJXybD6+cGxzTmuHIz9qQVproNWzHWKhP3cfO2mTA8Wyjcj4uLDl76IxO5kNKOzA4nSCQ1Fz1vuCG7mBaGmiUyoM8Rzn2bWKrXnZRfS8xden5g2qUzGcdKrXCp8LKkvMudXzk1Oy3mXcWz19KXAI2GjaAGnmAddO3mzH066UlK5awujjmW2tYQC3A1xDXgu7dqMHz5m5lZywdXDYUu24WfCS7huPlCCyetGLvPAUN04k0kjH8ToPJWqDsLrOi4DHcJWlNtPcYR20A/DCqffag3FuIGWDTDTvZdSM7ch3LGZ7YQRQzbSWQRSk1ZHoEgERv+m1DuafWUwgc7tr/RmbVs2JuCAShfUXvdi0oE7xIjuFe75Rwf7fCRxLWklOeojZvlBGewMTKULcReObFtcgNBZULQOrzwvx7w5DDvTGs0MZtsKvVU9RJgC+W8Ej/dNPPhO8liMSXLvOl9HdDa6LrialOasn7uZTiuOhh3YW7dBC/92iFKSnoXd80iJogzc41+U2hisxMC8MXXB9ax1n6G7TXVMdYUgm4fSxnyrMlGbp6PUsDeedkvcp3qW3a
  template:
    metadata:
      name: maas-db-config
      namespace: redhat-ai-gateway-infra
    type: Opaque
