apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stale-image-finder
  labels:
    app: stale-image-finder
    app.kubernetes.io/part-of: stale-image-finder
  annotations:
    haproxy.router.openshift.io/timeout: 300s
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains
spec:
  to:
    kind: Service
    name: stale-image-finder-dashboard
  port:
    targetPort: dashboard
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
