---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-api-secret
  namespace: autorag
spec:
  encryptedData:
    llm-api-key: AgCd95++GfBRewZO6XKXK5irOhKTLmw63j/gUXmmOgvBn9TXCfH2KTHDs0/3GOn4JQw6roJJESE+aAExrmGhuNpZRQB7GH5q+VQuoOcwNoYxlmdXwdT0Zv09My9hUznJ2eAw9jTss3eqDIaM0crxHrF6kgOob5BRt9vAQxDSUb86KMATilKDD+nTRTria99y6Su64ZkOl13gtsUjnFjFYUOpjes+U4t8vMUfc3pPg5m6qkROpMJ62pF/xSZG1MorjbCZMj4WwHIsa43+7kM/gmdC2rh4dGrZ4LKQPEuMt1YbROPKaxhWjVXnvYaLnxBDVvKbP/nAm63MNyNmdk+EFO53oxiPOG5tkT4NIr4dx8NZF0322OvuUQpgPByeVz51lTMR6ZZSqxKDetPeOBHFeHwQQtKbH8j/ITv3GOk9pshSJRmx0x6mQFoIPXLW5uUjik6meEfKRC+smWKFUdWxNfxCs4b66aD20+mw8NtaYy51nwiq4tl0/HRODoQzr/HPAMHrBjXrPt2vpGyAEVOAT+IP9C3MoF5DXAl95cTz4eKTXPPk3SbGTBQq7G5HhgBY8hEQSHO+GrUAeW6PoT4/S/gcAvgl8pbzXEF3I87gu5oMZmt98gnh+3Y85zwAHv8QgHLrkW10+lK6MfHC1xc9k0Zw7craVJJJm7fKGgfVQ1Vto793nw/u98r6A7F+3k6G0WgzeMwwvgvxVpEwmMlhlRNw
  template:
    metadata:
      name: llm-api-secret
      namespace: autorag
    type: Opaque
