---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-admin
  namespace: open-webui
spec:
  encryptedData:
    password: AgBMAIow9J7BgO3Z4djmoCfp5QOWly2SAYNzlN40IJiYSv+bTKyHhLVP8WWl2+oF/bB4i6C4GKoGnL2XW4tR7qBfzPlUNiFqg6kCDE1q0qqLGXkMYvBCOdtFvCLJL98YYtf1qcBEViKtvM9+NcKaQT4qdnOWdgsePprEINGRlSpgxT7oUbX4lk6H6ly8XEaBQaYZqM6dhj9Ed98z/ppm9NHIYBE07rfBckR93g5um2l+4l4yZOG/rsLISb3kLxSqBNGH/glwE4W1NiMynI7NLPb0VLjl0mNoTbs2lTXEHHipqfNQpn7vtCQrXH/2xGh4y4gLYdCGsRBXR0fGnOSSwq9OI3bu+QijLRLSIvZa647kNptbZ1ygerk7mkjRABrgoR9jVmFw60A0OSiYL8mABSpgi0UNjomsYTHzBmocA8IqDqThnytCseVsyrhpniMeiAIvmxFtGqY5xgZkgRITKt8w9uFO6GVfTXNtl1u6vKYhm4Pf0OPoC7BQuHIVME5IHPUJXMneAKzRY+yog73spANSwwUbk9yNBTffzN17fwNflWw2ISJ5o96dIL9OaDsRvOU7N0iBMDeHJTlXQFI/ic5HAX+1j7iju92MHsedESo/4GujrCEx5VkBLhAchfBVunmlpj9NtH2+Dt8jVPaSS3fFs9bB+9iqtrMVTMRTNNAbfNVeShc8LoFy89IlAy+pb1nJZBDLPlioSJRn9QYYNyl642jAxuI7ISZ2doaGKc3lOg==
  template:
    metadata:
      name: open-webui-admin
      namespace: open-webui
    type: Opaque
