---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oidc
  namespace: open-webui
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgB9OzM2KEM/Uh7jbT7yOEwsrjcnaYSZV4VV/bacAK4zKvG3yCU6wQjvHOMi7inyb4WwT93Qrd1G4hhBGHD+RFFSFsry0PgKMvNuD/yvcExXCLMUN1WZbY1rBHZuE0GkfjxizFZwJFTITnSVFjiyycQBRnBGSAFZECXnT91qCI/dKkOqNI7XkavzJGbM1PsQTz/uD/v/FE3TDtNFRrnLn+An9NQaNMx061aY4a36R5L3Rx1h3pXCKTL1Y2Xxae8li7qbmxjEygYFxNTGyWIvkfl2iVXoaYzN3uGNGd2oVavuSHeC4onmu1MYj1WkRjxxeudjI7z2wEKEZ8HMacVcRWcLmszwmmS2x+vJ7UQn0azDB//vIOpSuKb2Th3qniouqFoQMB6ebgK4G9n41n13I74Pd0Tct6/1wrw5p7dxPVQRYm7e8+jxBpotI1xYZVbrqfQ7yY8GbFoa+NUv+w1IB2XrxD4uwN9wKfqhibS7SuiYQ3kjj6LWe3EkI6rF+lOC9YDfvpyDHGn6sgHAJGAU1eWmMBThloSCm4oMtKlLDZwnO2BkR9z57wsqw8OHkU/szGplmFKk2nQrqwaXS6+OXyRXZVXe8PlCvWOxOd3qdbUyyGmbHa2nYYSGceAwb/CEY5m4qAPIPjhQBmojQPRFFUQQevQdRAo77oKO1RzYJVv6DqcFURPGlOMdphtfGJbMco4pB7KHRT2ZrayudqnLFxg+so5TcD1IGiPe3Gel4yia6SqcevhpUw66tuwH
  template:
    metadata:
      name: open-webui-oidc
      namespace: open-webui
    type: Opaque
