---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-admin
  namespace: open-webui
spec:
  encryptedData:
    email: AgB/xt43XIzCXpDA9uDM3NL03OD/36sl///P20LoyoKpLFvYuCC5zY9qy6KOdhvlw63OsJxtT5nZ6ohMH2kZIi3I53W8Pys9275aw+8Ye/QYbC5UVdMoiVtsfBsVHDLzUDWeKY0Uuuwt1NY6JlCVoTByf16jWPlR8mFpEIKAyaexU4n+b5tNkiX0g6Gg6swkPv7SPb3j9jPFdOWOkezyol9coOacWE0MJHXO8sneX9ROcPHWh0ohv1vtigOXC7XCzvqnwWThXZEVPHod1MJSTxDRQWju9DakZ9ZnV4mjePC27PkzW6Th85bFcTxRRV9m2Dv3RuFYc+bbkK8wMjosHoVubj4XyNL3qshmmLqsNi5gzrxJMZJil9bwDHqdGlC4vn3DNxkVlVZlFLoM38Ouym6RxVYbPh667wA9PouemQLIE1I+1cirN/5i16HqlODuOMEVZ57Bvd5NnjUzEuM4XPbTo4WpTZRheDCePhphHjZKBa1hF+9qYeyN/gz3B6RcP7p8gXGdEN/lKn+bCRxsH987GPbA9KCdZNBvXBITSuDrBBsu9ltTmPZnS9+OZfUSBln8EGMftouc1/DGBV4H8TWHJNpW/zmXR+5noGRAbuQ7Likn7UzeDKbqxRH3Sc6GaFxUzoIcDqY5TKngn/f2uHp3F/WY0Yp77GHOeUEzD07XMvOKHw5D8MusK1hj5dpVG6g2bWPys8EYwIlhVvnL7tPCFw==
    password: AgCYDCzD1AiCoNdoatziV7iSta5yRNGE0vpV0c/op+bynhO5lmLxyZycvwFeahmts+CtJl3R9qKhrr3cw5P2Xajlx0/h7U5YXcQQp/UFhI0mcpJOHcu9r7loMNO/WZ7A8IOMSJ+j1sBhP32b0jD5TXOTdqH9eGDsltl5jz/vrzPEZQN3RnyvI4pA5Pz81rzF6/Erdo31jg8MgjMycZiURhgymfi9qkGQoDAUTBHQKni0hH9EToiaNbVSJJK7nVg4BSuIS+tD+qVjWfbEnTf+egYZ8EDxQlF0VBKu+0WNZkI94E9hP0U8WsDHXYk/YEF0U66j1UCYX4wAo98kb7Hw6IVb20IgPI44Hj5S4YIwwXVs4QjchXF4BF7sNFxjetmzog3FBu92leDJkQPIbJDP6FzKcNP+YYw0MR7/JIbKeK+GYxAlxWhJZDnzWyS+CX8YMCLrLONT47MZQfwHhCZhUGwJMrgBvRfHLAiah9VYJ9ppA8AhNZZBiumoi5m1UDBAV3y9e/s64I0y+swA3wPcV4emZhFUcCwT94wFTd59b2kgK4pzbX2mEEwWDcu6JDmwWmhzzJ49+nZnyyQqDOkUdDDivbR0F2bxzJNDrR6Ib+Owlyd3ZYLzozduEYOE6stGhTvZmsEaYB4FFABxN8jBdRjPYrHy/bvYzpiaqODgbRhPPDwVaEhY7ZPrjMUZRZAoAsIVK9aRFw==
  template:
    metadata:
      name: open-webui-admin
      namespace: open-webui
    type: Opaque
