apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-output
  labels:
    app: spark-data-ingestion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
