apiVersion: v1
kind: Namespace
metadata:
  name: mcp-system
  annotations:
    openshift.io/display-name: "MCP Gateway"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mcp-gateway
  namespace: mcp-system
spec:
  gatewayClassName: openshift-ai-inference
  listeners:
    - name: mcp
      hostname: mcp-gateway-mcp-system.apps.ocp.qn6c5.sandbox1388.opentlc.com
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: mcps
      hostname: "*.mcp.local"
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-mcp-gateway
  namespace: mcp-system
spec:
  from:
    - group: mcp.kuadrant.io
      kind: MCPGatewayExtension
      namespace: openshift-operators
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: openshift-operators
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: ocp-mcp-server
    - group: kuadrant.io
      kind: AuthPolicy
      namespace: mcp-system
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
