apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  name: fine-tuning-demo
  namespace: rhoai-model-registries
spec:
  grpc:
    port: 9090
  rest:
    port: 8080
    serviceRoute: enabled
  postgres:
    generateDeployment: true
    sslMode: disable
