apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-deploy
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rrbanda/ai-platforms.git
    targetRevision: main
    path: redhat/rhoai/v3.5/base/applications
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
