apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPGatewayExtension
metadata:
  name: mcp-gateway-extension
  namespace: mcp-gateway-system
spec:
  publicHost: MCP_GATEWAY_HOSTNAME_PLACEHOLDER
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: mcp-gateway
    namespace: mcp-system
    sectionName: mcp
  httpRouteManagement: Enabled
