apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-agent

resources:
  - sandbox.yaml
  - startup.yaml
  - service.yaml
  - route.yaml
  - soul.yaml
  - config.yaml
  - restart-hook.yaml
  - restart-rbac.yaml
  - skills/skill-demo-assistant.yaml

configMapGenerator:
- name: demo-agent-openshell-policy
  files:
  - sandbox-policy.rego
  - policy.yaml

generatorOptions:
  disableNameSuffixHash: true
