apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-cluster-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: rhoai-config
  source:
    repoURL: https://github.com/rrbanda/ai-platforms.git
    targetRevision: main
    path: redhat/rhoai/v3.5/overlays/sandbox1388/config
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-applications
  ignoreDifferences:
    - group: security.openshift.io
      kind: SecurityContextConstraints
      jsonPointers:
        - /allowPrivilegeEscalation
        - /allowedCapabilities
        - /defaultAddCapabilities
        - /requiredDropCapabilities
        - /priority
        - /readOnlyRootFilesystem
        - /groups
        - /userNamespaceLevel
        - /volumes
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
