apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/02-config
  - sealed-maas-postgres-credentials.yaml
  - sealed-maas-db-config.yaml
  - sealed-maas-gateway-tls.yaml
