apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openshell
  namespace: openshell
spec:
  to:
    kind: Service
    name: openshell
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
