apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rfp-agent-eval

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - eval-job.yaml
  - collection.yaml
